---
# tasks file for stargate-v0
- name: Namespace for stargate-v0
  community.kubernetes.k8s:
    state: "{{ stargate_state }}"
    name: "{{ stargate_namespace }}"
    api_version: v1
    kind: Namespace

- name: stargate-v0 service
  community.kubernetes.k8s:
    state: "{{ stargate_state }}"
    namespace: "{{ stargate_namespace }}"
    template: "{{ item }}"
  with_items:
    - auth.yml.j2
    - web.yml.j2
    - ingress.yml.j2
  tags:
    - stargate-v0
